-- Modified for ForeverAuras
-- Modifications Copyright (C) 2026 ForeverAuras. Licensed under the GNU GPL v2 (see LICENSE).
if not WeakAuras.IsLibsOK() then return end
---@class OptionsPrivate
local OptionsPrivate = select(2, ...)

OptionsPrivate.IconLibrary = {
  root = "Interface\\AddOns\\ForeverAuras\\Media\\Icons\\",
  folders = {
    { name = "Assets", path = "Assets\\", files = {
      "arrow_down.tga", "arrow_left.tga", "arrow_right.tga", "arrow_up.tga", "check.tga", "chevron.tga",
      "clock.tga", "cross.tga", "diamond.tga", "dot.tga", "exclamation.tga", "gear.tga",
      "play.tga", "reset.tga", "ring.tga", "role_damage.tga", "role_damage_badge.tga", "role_damage_color.tga",
      "role_healer.tga", "role_healer_badge.tga", "role_healer_color.tga", "role_tank.tga", "role_tank_badge.tga", "role_tank_color.tga",
      "star.tga", "stop.tga", "target.tga",
    },
    game = {
      { "Raid Marker Star", 137001 },
      { "Raid Marker Circle", 137002 },
      { "Raid Marker Diamond", 137003 },
      { "Raid Marker Triangle", 137004 },
      { "Raid Marker Moon", 137005 },
      { "Raid Marker Square", 137006 },
      { "Raid Marker Cross", 137007 },
      { "Raid Marker Skull", 137008 },
      { "Ready Check Ready", 136814 },
      { "Ready Check Not Ready", 136813 },
      { "Ready Check Waiting", 136815 },
    },
    },
    { name = "Emojis", path = "Emojis\\", files = {
      "0Head.tga", "1Head.tga", "2Head.tga", "3Head.tga", "3Lass.tga", "4HEad.tga",
      "4HEader.tga", "4House.tga", "4Mansion.tga", "4peepo.tga", "4Shrug.tga", "4Weird.tga",
      "4WeirdW.tga", "5Champ.tga", "5Hard.tga", "5Head.tga", "AMAZINGA.tga", "ANGERY.tga",
      "AngeryCry.tga", "Angy.tga", "asmonPower.tga", "Awakge.tga", "AYAYARR.tga", "AYAYAWeird.tga",
      "BaconEffect.tga", "BBona.tga", "BearDab.tga", "Bedge.tga", "Bedges.tga", "BedgeTogether.tga",
      "BigNars.tga", "BinCat.tga", "binocs.tga", "BlackKnight.tga", "BLUBBERS.tga", "Blushge.tga",
      "BOGGED.tga", "BOOFA.tga", "Boolin.tga", "Boomer.tga", "Borpa.tga", "BorpaL.tga",
      "BorpaU.tga", "Breadclown.tga", "Britpega.tga", "BroKiss.tga", "bUrself.tga", "Bwonsambee.tga",
      "CatChest.tga", "Catge.tga", "ChagU.tga", "CHAMPERS.tga", "ChampU.tga", "checkdoggo.tga",
      "ChogPamp.tga", "Chomp.tga", "CiGrip.tga", "CloakofShadows.tga", "ClownBall.tga", "Clownge.tga",
      "ClownPain.tga", "cmoB.tga", "cmoN1.tga", "cmonBruv.tga", "cmonEyes.tga", "cmoV.tga",
      "COGGERS.tga", "ConcernDoge.tga", "Coomer.tga", "Copege.tga", "COPIUM.tga", "coronaS.tga",
      "CrazyChamp.tga", "CringeW.tga", "CROGGERS.tga", "Cryge.tga", "CutePepe.tga", "danebrain.tga",
      "DankHug.tga", "Deadge.tga", "deadgemines.tga", "DeadgeTogether.tga", "dejj.tga", "Despairge.tga",
      "DidntAsk.tga", "DIDSOMEONESAYCOCK.tga", "DinkDonk.tga", "DisappointChamp.tga", "DKKona.tga", "DogeKek.tga",
      "DogeWitIt.tga", "done.tga", "DragonAww.tga", "DragonCozy.tga", "DragonCry.tga", "DragonFat.tga",
      "DragonREE.tga", "DragonSip.tga", "DragonThink.tga", "DragonWave.tga", "duckieW.tga", "ehWTF.tga",
      "ELE.tga", "emDface.tga", "eShrug.tga", "espanLOL.tga", "EVILSMILERS.tga", "ExitG.tga",
      "EZ.tga", "EZChamp.tga", "FapFapFap.tga", "FARTIUM.tga", "FatBod.tga", "FatCat.tga",
      "FatDank.tga", "Fatge.tga", "FeelsAllianceMan.tga", "FeelsAmazingMan.tga", "FeelsBadMan.tga", "FeelsBadManF.tga",
      "FeelsBadManV.tga", "FeelsBadW.tga", "FeelsBetaMan.tga", "FeelsBirthdayMan.tga", "feelsblob.tga", "FeelsBlushMan.tga",
      "FeelsBoomieMan.tga", "FeelsBoredMan.tga", "FeelsComradeMan.tga", "FeelsCoolMan.tga", "FeelsCopterMan.tga", "FeelsCringeMan.tga",
      "FeelsCryMan.tga", "FeelsCuteMan.tga", "FeelsDabMan.tga", "FeelsDeadMan.tga", "FeelsDorkMan.tga", "FeelsDrunkMan.tga",
      "FeelsDutchMan.tga", "FeelsEleMan.tga", "FeelsEvilMan.tga", "FeelsFatMan.tga", "FeelsGamerMan.tga", "FeelsGermanMan.tga",
      "FeelsGoodEnoughMan.tga", "FeelsGoodMan.tga", "FeelsGreatMan.tga", "FeelsGreekMan.tga", "FeelsHordeMan.tga", "FeelsHug.tga",
      "FeelsHugged.tga", "FeelsHunterMan.tga", "FeelsIncredibleMan.tga", "FeelsLitMan.tga", "FeelsLoveManW.tga", "FeelsMyFingerMan.tga",
      "FeelsNewYear.tga", "FeelsOakyMan.tga", "FeelsOkayMan.tga", "FeelsOldMan.tga", "FeelsPinkMan.tga", "FeelsPumpkinMan.tga",
      "FeelsRainSadge.tga", "FeelsRottenMan.tga", "FeelsSad.tga", "FeelsSadMan.tga", "FeelsShadowMan.tga", "FeelsSleepyMan.tga",
      "FeelsSnowMan.tga", "FeelsSnowyMan.tga", "FeelsSorryMan.tga", "FeelsStrongMan.tga", "FeelsSuicideMan.tga", "FeelsTankMan.tga",
      "FeelsTastyMan.tga", "FeelsThinkingMan.tga", "FeelsTired.tga", "FeelsTiredAF.tga", "FeelsUnsureMan.tga", "FeelsWeirdMan.tga",
      "FeelsWiredMan.tga", "FeelsWowMan.tga", "fingi.tga", "FishMoley.tga", "FLOPPERS.tga", "fml.tga",
      "ForeverAlone.tga", "FrogO.tga", "Frostbitchyes.tga", "FUARK.tga", "FuckYea.tga", "GabeN.tga",
      "gachiGASM.tga", "Gayge.tga", "Gerdlerk1.tga", "Gerdlerk2.tga", "Gerdlerk3.tga", "Gerdlerk4.tga",
      "GiggleHands.tga", "GIMMIE.tga", "Gladge.tga", "gladgers.tga", "goodd.tga", "GoodW.tga",
      "greekDitch.tga", "greekLOUDER.tga", "guna.tga", "gXD.tga", "HabibiPrayge.tga", "HACKERMANS.tga",
      "HammersArk.tga", "HammersNoArk.tga", "HammerTime.tga", "HandsUp.tga", "HappyJammies.tga", "Heartato.tga",
      "HerbPerve.tga", "Hhhehehe.tga", "HmmChamp.tga", "Hmmge.tga", "Hmmmge.tga", "hoboW.tga",
      "HomieL.tga", "HomieR.tga", "HYPERBRUH.tga", "HYPERDANSGAME.tga", "HYPERDANSGAMEW.tga", "HYPEROMEGALUL.tga",
      "HYPEROMEGAPOGGERSCRAZY.tga", "HYPERS.tga", "HYPERTHONK.tga", "imKEKWing.tga", "imOkayChamp.tga", "InspectorAngryWoof.tga",
      "InspectorAngryWoofM.tga", "JanCarlo.tga", "jerryWhat.tga", "Joy2.tga", "Joy3.tga", "just.tga",
      "Kaged.tga", "Kapp.tga", "KEKE.tga", "KekeHands.tga", "KEKGA.tga", "KEKL.tga",
      "KEKLeo.tga", "KEKPog.tga", "KEKpoint.tga", "KEKSad.tga", "kekW.tga", "KEKWeird.tga",
      "KEKWHands.tga", "KEKWPog.tga", "Kermitpls.tga", "KKomrade.tga", "KKona.tga", "KKonaW.tga",
      "KKonductor.tga", "KKool.tga", "Krappa.tga", "LaughW.tga", "lethink.tga", "LilZ.tga",
      "LMAO.tga", "lookdown.tga", "lookup.tga", "Lovepeepo.tga", "Lovge.tga", "LUL.tga",
      "LULChamp.tga", "LULE.tga", "LULERS.tga", "LULW.tga", "LULWW.tga", "Lyeasy.tga",
      "LyeCute.tga", "LyeREE.tga", "LyeShrug.tga", "LyEZ.tga", "Madge.tga", "MadgeBackhand.tga",
      "MadgeClap.tga", "Madgee.tga", "MadgeNow.tga", "MadgeRightNow.tga", "majj.tga", "MaldChamp.tga",
      "MALDD.tga", "MamaMiaItaliano.tga", "MaN.tga", "maximumautism.tga", "Maya.tga", "meAutism.tga",
      "MEGALUL.tga", "MEGALUL_2.tga", "memebeam1.tga", "memebeam2.tga", "memebeam3.tga", "MingLuL.tga",
      "monakGun.tga", "monakHmm.tga", "Monaks1.tga", "monakW.tga", "monkaANELE.tga", "monkaBlanket.tga",
      "monkaCapture.tga", "monkaChrist.tga", "monkaD.tga", "monkaEyes.tga", "monkaGasp.tga", "monkaGIGA.tga",
      "monkaGun.tga", "monkaH.tga", "monkaHands.tga", "monkaHmm.tga", "monkaJail.tga", "monkaKek.tga",
      "monkaLaugh.tga", "monkaMEGA.tga", "monkaOh.tga", "monkaOMEGA.tga", "monkaPickle.tga", "monkaS.tga",
      "Monkas1.tga", "monkaShake.tga", "monkaStab.tga", "monkaStare.tga", "monkaStop.tga", "monkaSusp.tga",
      "monkaT.tga", "monkaThink.tga", "monkaTOS.tga", "monkaU.tga", "monkaVirus.tga", "monkaW.tga",
      "monkaWCB.tga", "monkaYou.tga", "monkerS.tga", "NA.tga", "NaM.tga", "nanoMEGA.tga",
      "NeckBeard.tga", "needcopium.tga", "NeedCopiumPepe.tga", "needdrama.tga", "needmemes1.tga", "needmemes2.tga",
      "Nerdge.tga", "NickyQ.tga", "noClown.tga", "NOOBA.tga", "NOP.tga", "NotLike.tga",
      "Notsurege.tga", "noxSorry.tga", "noxWhat.tga", "OhISee.tga", "OhYouSee.tga", "OkayChamp.tga",
      "OkayChomp.tga", "Okayeg.tga", "Okayga.tga", "Okayge.tga", "OkaygeShrug.tga", "OkayLaugh.tga",
      "OkayW.tga", "OldChamp.tga", "oldpepe.tga", "OMEGAEZ.tga", "OMEGAKEKW.tga", "OMEGALUL.tga",
      "OMEGASP.tga", "OMEGATriHard.tga", "oniongang.tga", "oof.tga", "PagChomp.tga", "PagMan.tga",
      "PainsChamp.tga", "PantsGrab.tga", "PATHETIC.tga", "PauseChamp.tga", "PAUSERS.tga", "Pausey.tga",
      "PBear.tga", "peep.tga", "peepaGrown.tga", "peepaKiss.tga", "peepaSexy.tga", "PeepGiggle.tga",
      "PeepHand.tga", "PeepKek.tga", "PeepLaugh.tga", "peepoAlliance.tga", "peepoAP.tga", "peepoBaba.tga",
      "peepoBeer.tga", "peepoBlankey.tga", "peepoBlush.tga", "peepoBlushing.tga", "peepoBored.tga", "peepoBritish.tga",
      "peepoBye.tga", "peepoCharge.tga", "peepoCheer.tga", "peepoChonk.tga", "peepoClap.tga", "peepoCN.tga",
      "peepoCringe.tga", "peepoCrown.tga", "peepoCute.tga", "peepoDab.tga", "peepoDE.tga", "peepoDetective.tga",
      "peepoDetective2.tga", "peepoES.tga", "peepoEU.tga", "peepoEvilSip.tga", "peepoExit.tga", "peepoEyes.tga",
      "peepoEZ.tga", "peepoFA.tga", "peepoFat.tga", "peepoFH.tga", "peepoFight.tga", "peepoFoil.tga",
      "peepoFR1.tga", "peepoFR2.tga", "peepoFriends.tga", "peepoFrogHappy.tga", "peepoGift.tga", "peepoGlad.tga",
      "peepoGun.tga", "peepoH.tga", "peepoHands.tga", "peepoHeart.tga", "peepoHeHe.tga", "peepoHey.tga",
      "peepoHide.tga", "peepoHmm.tga", "peepoHug.tga", "peepoHugged.tga", "peepoHuggiesL.tga", "peepoHuggiesR.tga",
      "peepoIgnore.tga", "peepoIsForMe.tga", "peepoJail.tga", "peepoJammies.tga", "peepoJedi.tga", "peepoJorts.tga",
      "peepoJudge.tga", "peepoJuice.tga", "peepOK.tga", "peepoKEKW.tga", "peepoKing.tga", "peepoKiss.tga",
      "peepoKnight.tga", "peepoLip.tga", "peepoLoser.tga", "peepoLove.tga", "peepoM.tga", "peepoMadder.tga",
      "peepoMaybe.tga", "peepoNice.tga", "peepoNo.tga", "peepoNolegs.tga", "peepoNOO.tga", "peepoNOOO.tga",
      "peepoNotes.tga", "peepoOK.tga", "peepoPanda.tga", "peepoPants.tga", "peepoParty.tga", "peepoPee.tga",
      "peepoPeek.tga", "peepoPing.tga", "peepoPlease.tga", "peepoPlot.tga", "peepoPogPoo.tga", "peepoPoint.tga",
      "peepoPoo.tga", "peepoPopcorn.tga", "peepoPride.tga", "peepoRain.tga", "peepoReallyHappy.tga", "peepoS.tga",
      "peepoSadCat.tga", "peepoSadLogize.tga", "peepoSalute.tga", "peepoScam.tga", "peepoSE.tga", "peepoSenor.tga",
      "peepoShower.tga", "peepoShrug.tga", "peepoShy.tga", "peepoSick.tga", "peepoSimp.tga", "peepoSimping.tga",
      "peepoSip.tga", "peepoSith.tga", "peepoSleepo.tga", "peepoSmile.tga", "peepoSoup.tga", "peepoSPopcorn.tga",
      "peepoStab.tga", "peepoStonks.tga", "peepoStudy.tga", "peepoSure.tga", "peepoSuspect.tga", "peepoSuspicious.tga",
      "peepoSweat.tga", "peepoTeddy.tga", "peepoTeeth.tga", "peepoThink.tga", "peepoTip.tga", "peepoTired.tga",
      "peepoTrash.tga", "peepoUgh.tga", "peepoUK.tga", "peepoUSA.tga", "peepoWave.tga", "peepoWeird.tga",
      "peepoWeirdCrown.tga", "peepoWhy.tga", "peepoWoW.tga", "peepoWTF.tga", "PepeAyy.tga", "PepeBean.tga",
      "pepeBlyat.tga", "pepeBruh.tga", "PepeButt.tga", "PepeCat.tga", "PepeCatGun.tga", "PepeCatHeart.tga",
      "PepeCoffee.tga", "PepeCoolStory.tga", "PepeCozy.tga", "PepeDent.tga", "PepeDisgust.tga", "PepeDribble.tga",
      "PepeFeet.tga", "PepeFinger.tga", "PepeFist.tga", "PepeFlushed.tga", "PepeFork.tga", "PepeFrench.tga",
      "PepeFU.tga", "PepeFuming.tga", "PepeG.tga", "Pepega.tga", "PepegaHammer.tga", "PepegaHands.tga",
      "PepegaKMS.tga", "PepegaLaugh.tga", "PepeGamer.tga", "pepeGang.tga", "PepegaPoo.tga", "PepegaS.tga",
      "PepegaSad.tga", "Pepege.tga", "PepegeS.tga", "PepegeSit.tga", "PepegeWeird.tga", "Pepeggers.tga",
      "Pepegwa.tga", "pepeHam.tga", "PepeHands.tga", "PepeHard.tga", "PepeHeart.tga", "PepeHug.tga",
      "PepeIgnore.tga", "PepeKMS.tga", "PepeL.tga", "PepeLa.tga", "PepeLaffe.tga", "PepeLaugh.tga",
      "PepeLegs.tga", "PepeLMAO.tga", "PepeLoser.tga", "PepeLove.tga", "PepeM.tga", "PepeManos.tga",
      "PepeMegaSad.tga", "PepeMods.tga", "PepeMStache.tga", "PepeNo.tga", "pepeNotOK.tga", "pepeOK.tga",
      "PepeOuuuhh.tga", "Pepepains.tga", "PepePants.tga", "PepePhone.tga", "PepePhoned.tga", "PepePlan.tga",
      "PepePoint.tga", "PepePoo.tga", "PepePopcorn.tga", "PePeppaPig.tga", "PepePuke.tga", "PepePyroblast.tga",
      "PepeReach.tga", "PepeRun.tga", "PepeScoots.tga", "PepeScout.tga", "PepeSlice.tga", "PepeSmile.tga",
      "PepeSmoke.tga", "pepeStepBro.tga", "PepeStressed.tga", "PepeTHICC.tga", "PepeThumbsUp.tga", "PepeUnicorn.tga",
      "pepeW.tga", "PepeWhip.tga", "PepeWizard.tga", "PepeWot.tga", "PepeXD.tga", "PepeYes.tga",
      "pepoEZ.tga", "pepoGun.tga", "pepohide.tga", "PepOMEGA.tga", "pepoS.tga", "pepoScience.tga",
      "PepoThink.tga", "PepperHands.tga", "Pho.tga", "PikaWOW.tga", "pillowJammies.tga", "Pog.tga",
      "pOg1.tga", "PogClappa.tga", "Pogey.tga", "PogeyU.tga", "pogg.tga", "POGGAROO.tga",
      "POGGERS.tga", "POGGERSF.tga", "PoggersHype.tga", "PoggersHypeF.tga", "POGGERSLove.tga", "Poghurt.tga",
      "PogMe.tga", "PogO.tga", "PogO2.tga", "PogOff.tga", "Pogomega.tga", "PogOW.tga",
      "PogU.tga", "PogWarts.tga", "PogYou.tga", "POOGERS.tga", "PotFriend.tga", "PowerUpL.tga",
      "PowerUpR.tga", "PPepoCool.tga", "PPepoHit.tga", "ppEZ.tga", "ppFootbol.tga", "PPirate.tga",
      "ppSmoke.tga", "PraiseTheSun.tga", "Prayge.tga", "RandomPepe.tga", "Ratge.tga", "Readge.tga",
      "REEE.tga", "Riotge.tga", "RowFish.tga", "RowSalt.tga", "SadBlanket.tga", "SadCash.tga",
      "SadCatWave.tga", "SadChamp.tga", "Sadga.tga", "sadgers.tga", "SadHonk.tga", "sadhug.tga",
      "SadJAM.tga", "SadLove.tga", "SadOke.tga", "SadPepe.tga", "SAJ.tga", "sajj.tga",
      "SaladPepega.tga", "salutt.tga", "savixHappy.tga", "SchubertaBruh.tga", "SchubertBruh.tga", "SchubertSmile.tga",
      "shrujj.tga", "shy.tga", "SillyChamp.tga", "Sk.tga", "SkDead.tga", "SkEvil.tga",
      "SkGasm.tga", "skip.tga", "SkMad.tga", "SkNervous.tga", "SkSad.tga", "SkSmile.tga",
      "SkSpook.tga", "SkWeird.tga", "SkWink.tga", "Smadge.tga", "SmileHard.tga", "Smilers.tga",
      "Smoge.tga", "SMUGGERS.tga", "SmugPepe.tga", "sosig.tga", "sosigW.tga", "soupchamp.tga",
      "spit1.tga", "spit2.tga", "squawk.tga", "stabby.tga", "StareBruh.tga", "StareChamp.tga",
      "Starege.tga", "Stronge.tga", "SucksMan.tga", "Susge.tga", "Suske.tga", "thehmm.tga",
      "thethink.tga", "Thonk.tga", "ThrallS.tga", "tip.tga", "TiredW.tga", "tomatogang.tga",
      "tooDank.tga", "TOSga.tga", "trash.tga", "TriEasy.tga", "TriGold.tga", "TriHardS.tga",
      "TriKool.tga", "TriPeek.tga", "TriTasty.tga", "TroggHYPERS.tga", "UHM.tga", "VaN.tga",
      "VapeNation.tga", "Voidge.tga", "wardog.tga", "WeirdBruh.tga", "WeirdChamp.tga", "WeirdChampion.tga",
      "Weirders.tga", "Weirdga.tga", "Weirdge.tga", "WeirdJAM.tga", "WeirdU.tga", "WeirdW.tga",
      "welp.tga", "weSmart.tga", "WhiteKnight.tga", "WickedDrip.tga", "Wipege.tga", "WOAW.tga",
      "Wokege.tga", "Wokegesus.tga", "Wowee.tga", "WULL.tga", "WutChamp.tga", "YAMERO.tga",
      "YEP.tga", "Yepge.tga", "YIKERS.tga", "YUM.tga", "ZFeral.tga", "ZkkOna.tga",
      "ZOINKS.tga", "Zoomer.tga", "ZShelia.tga", "ZULOL.tga", "ZULUL.tga", "zxEpic.tga",
      "zxGary.tga", "ZXSaiko.tga",
    },
    },
    { name = "FojjiCore", path = "FojjiCore\\", files = {
      "1107-icon.tga", "1108-icon.tga", "1109-icon.tga", "1110-icon.tga", "1111-icon.tga", "1112-icon.tga",
      "1113-icon.tga", "1114-icon.tga", "1115-icon.tga", "1116-icon.tga", "1117-icon.tga", "1118-icon.tga",
      "1119-icon.tga", "1120-icon.tga", "1121-icon.tga", "Abomination.tga", "akama.tga", "akilzon.tga",
      "alar.tga", "anetheron.tga", "arcane_missiles.tga", "arcane_missiles_1.tga", "arcane_missiles_2.tga", "arcane_missiles_3.tga",
      "ArcaneSnek.tga", "archimonde.tga", "archimonde_tbc.tga", "ArrowDown.tga", "ArrowDownWhite.tga", "ArrowUp.tga",
      "ArrowUpWhite.tga", "art_of_war.tga", "azgalor.tga", "Back_1_Overlay.tga", "Back_2_Overlay.tga", "backlash.tga",
      "backlash_green.tga", "bandits_guile.tga", "Banshee.tga", "Bashful.tga", "Berserk.tga", "blood_boil.tga",
      "blood_surge.tga", "Bowling.tga", "brain_freeze.tga", "brutallus.tga", "cast_shield.tga", "council.tga",
      "CryptFiend.tga", "dark_tiger.tga", "dark_transformation.tga", "daybreak.tga", "demonic_core.tga", "demonic_core_vertical.tga",
      "denounce.tga", "discicon_nuHordev2.tga", "echo_of_the_elements.tga", "eclipse_moon.tga", "eclipse_sun.tga", "F_icon_blue.tga",
      "F_icon_brown.tga", "F_icon_green.tga", "F_icon_lightblue.tga", "F_icon_orange.tga", "F_icon_purple.tga", "F_icon_red.tga",
      "F_icon_teal.tga", "F_icon_yellow.tga", "felmyst.tga", "feral_omenofclarity.tga", "FireSnek.tga", "focus_fire.tga",
      "Fojji_Banner_Blue.tga", "Fojji_Banner_Red.tga", "Fojji_F.tga", "Fojji_YTB.tga", "Fojji_YTR.tga", "FojjiBlue.tga",
      "fojjiHEART.tga", "fojjiLuL.tga", "fojjiMEOW.tga", "FojjiRed.tga", "fojjiSIP.tga", "FrostSnek.tga",
      "FrostWyrm.tga", "FROZEN_FINGERS.tga", "fulmination.tga", "fury_of_stormrage.tga", "Gargoyle.tga", "GarySnail.tga",
      "genericarc_01.tga", "genericarc_02.tga", "genericarc_03.tga", "genericarc_04.tga", "genericarc_05.tga", "genericarc_06.tga",
      "generictop_01.tga", "generictop_02.tga", "Ghoul.tga", "grand_crusader.tga", "gruul.tga", "gruul_tbc.tga",
      "gurtogg.tga", "hand_of_light.tga", "high_tide.tga", "HOT_STREAK.tga", "hydross.tga", "hydross_tbc.tga",
      "illidan.tga", "illidan_tbc.tga", "illidandemon.tga", "imp_empowerment.tga", "imp_empowerment_green.tga", "impact.tga",
      "Jaina.tga", "janalai.tga", "JoardeeKid.tga", "JoardePog.tga", "kaelthas.tga", "kaelthas_tbc.tga",
      "kalecgos.tga", "karathress.tga", "kazrogal.tga", "kiljaedan.tga", "kiljaedan_tbc.tga", "killing_machine.tga",
      "Left_1_Overlay.tga", "Left_2_Overlay.tga", "leotheras.tga", "Lightsaber.tga", "lock_and_load.tga", "lurker.tga",
      "maelstrom_weapon.tga", "maelstrom_weapon_1.tga", "maelstrom_weapon_2.tga", "maelstrom_weapon_3.tga", "maelstrom_weapon_4.tga", "magtheridon.tga",
      "magtheridon_tbc.tga", "malacrass.tga", "malchezar.tga", "malchezar_tbc.tga", "MarioCoin.tga", "MarioKart1.tga",
      "MarioKart2.tga", "MarioKart3.tga", "MarioKartGraphicsGo.tga", "mask.blp", "maskzero.blp", "master_marksman.tga",
      "molten_core.tga", "molten_core_green.tga", "monk_blackoutkick.tga", "monk_ox.tga", "monk_ox_2.tga", "monk_ox_3.tga",
      "monk_serpent.tga", "monk_tiger.tga", "monk_tigerpalm.tga", "muru.tga", "najentus.tga", "nalorakk.tga",
      "natures_grace.tga", "NatureSnek.tga", "Necromancer.tga", "necropolis.tga", "nightfall.tga", "nuLogo_Alliance.tga",
      "nuLogo_GOLD.tga", "nuLogo_GOLDRED.tga", "nuLogo_GREEN.tga", "nuLogo_LIGHTBLUE.tga", "nuLogo_MOPGOLD.tga", "nuLogo_RED.tga",
      "nuLogo_REDORANGE.tga", "nuLogo_SHAGREEN.tga", "nuLogo_WHITE.tga", "nuLogo_WHITERED.tga", "nyan.tga", "OLDEclipse_Moon.tga",
      "OLDEclipse_Sun.tga", "opera.tga", "predatory_swiftness.tga", "predatory_swiftness_green.tga", "ragewinterchill.tga", "raging_blow.tga",
      "reliquary.tga", "Right_1_Overlay.tga", "Right_2_Overlay.tga", "rime.tga", "serendipity.tga", "shadow_of_death.tga",
      "shadow_word_insanity.tga", "shahraz.tga", "ShaPagoda.tga", "Shell-Green-icon.tga", "shooting_stars.tga", "slice_and_dice.tga",
      "solarian.tga", "SombreroHat.tga", "SonicRing.tga", "spellactivationoverlay_0.tga", "sudden_death.tga", "sudden_death_red.tga",
      "sudden_doom.tga", "supremus.tga", "surge_of_darkness.tga", "surge_of_light.tga", "sword_and_board.tga", "t_star3.tga",
      "teron.tga", "Terrorists.tga", "Tetsuhands.tga", "TetsuPog.tga", "Thrall.tga", "thrill_of_the_hunt_1.tga",
      "thrill_of_the_hunt_2.tga", "thrill_of_the_hunt_3.tga", "tidewalker.tga", "tooth_and_claw.tga", "twins.tga", "TwinsOverlayChiji.tga",
      "TwinsOverlayNiuzao.tga", "TwinsOverlayXuen.tga", "TwinsOverlayYulon.tga", "TwinsRoom.tga", "ultimatum.tga", "vashj.tga",
      "vashj_tbc.tga", "voidreaver.tga", "Weapon_c4.tga", "white_tiger.tga", "zuljin.tga",
    },
    },
  },
}
