-- Modified for ForeverAuras
-- Modifications Copyright (C) 2026 ForeverAuras. Licensed under the GNU GPL v2 (see LICENSE).
if not WeakAuras.IsLibsOK() then return end
---@class OptionsPrivate
local OptionsPrivate = select(2, ...)

-- FojjiCore's textures are listed from its install (FojjiCore 3.1.8) and only offered
-- while FojjiCore is loaded; the files stay in FojjiCore. Each folder may set its own root.
local FOJJI_ROOT = "Interface\\AddOns\\FojjiCore\\textures\\"

function OptionsPrivate.IconFolderAvailable(folder)
  if not folder.addon then return true end
  local IsLoaded = C_AddOns and C_AddOns.IsAddOnLoaded or IsAddOnLoaded
  return IsLoaded ~= nil and IsLoaded(folder.addon) == true
end

OptionsPrivate.IconLibrary = {
  root = "Interface\\AddOns\\ForeverAuras\\Media\\Icons\\",
  folders = {
    { name = "Assets", path = "Assets\\", files = {
      "arrow_down.tga", "arrow_left.tga", "arrow_right.tga", "arrow_up.tga", "check.tga", "chevron.tga",
      "clock.tga", "cross.tga", "diamond.tga", "dot.tga", "exclamation.tga", "gear.tga",
      "play.tga", "reset.tga", "ring.tga", "role_damage.tga", "role_damage_badge.tga", "role_damage_color.tga",
      "role_healer.tga", "role_healer_badge.tga", "role_healer_color.tga", "role_tank.tga", "role_tank_badge.tga", "role_tank_color.tga",
      "star.tga", "stop.tga", "target.tga",
    },
    game = {
      { "Raid Marker Star", 137001 },
      { "Raid Marker Circle", 137002 },
      { "Raid Marker Diamond", 137003 },
      { "Raid Marker Triangle", 137004 },
      { "Raid Marker Moon", 137005 },
      { "Raid Marker Square", 137006 },
      { "Raid Marker Cross", 137007 },
      { "Raid Marker Skull", 137008 },
      { "Ready Check Ready", 136814 },
      { "Ready Check Not Ready", 136813 },
      { "Ready Check Waiting", 136815 },
    },
    },
    { name = "Emojis", path = "Emojis\\", files = {
      "0Head.tga", "1Head.tga", "2Head.tga", "3Head.tga", "3Lass.tga", "4HEad.tga",
      "4HEader.tga", "4House.tga", "4Mansion.tga", "4peepo.tga", "4Shrug.tga", "4Weird.tga",
      "4WeirdW.tga", "5Champ.tga", "5Hard.tga", "5Head.tga", "AMAZINGA.tga", "ANGERY.tga",
      "AngeryCry.tga", "Angy.tga", "asmonPower.tga", "Awakge.tga", "AYAYARR.tga", "AYAYAWeird.tga",
      "BaconEffect.tga", "BBona.tga", "BearDab.tga", "Bedge.tga", "Bedges.tga", "BedgeTogether.tga",
      "BigNars.tga", "BinCat.tga", "binocs.tga", "BlackKnight.tga", "BLUBBERS.tga", "Blushge.tga",
      "BOGGED.tga", "BOOFA.tga", "Boolin.tga", "Boomer.tga", "Borpa.tga", "BorpaL.tga",
      "BorpaU.tga", "Breadclown.tga", "Britpega.tga", "BroKiss.tga", "bUrself.tga", "Bwonsambee.tga",
      "CatChest.tga", "Catge.tga", "ChagU.tga", "CHAMPERS.tga", "ChampU.tga", "checkdoggo.tga",
      "ChogPamp.tga", "Chomp.tga", "CiGrip.tga", "CloakofShadows.tga", "ClownBall.tga", "Clownge.tga",
      "ClownPain.tga", "cmoB.tga", "cmoN1.tga", "cmonBruv.tga", "cmonEyes.tga", "cmoV.tga",
      "COGGERS.tga", "ConcernDoge.tga", "Coomer.tga", "Copege.tga", "COPIUM.tga", "coronaS.tga",
      "CrazyChamp.tga", "CringeW.tga", "CROGGERS.tga", "Cryge.tga", "CutePepe.tga", "danebrain.tga",
      "DankHug.tga", "Deadge.tga", "deadgemines.tga", "DeadgeTogether.tga", "dejj.tga", "Despairge.tga",
      "DidntAsk.tga", "DIDSOMEONESAYCOCK.tga", "DinkDonk.tga", "DisappointChamp.tga", "DKKona.tga", "DogeKek.tga",
      "DogeWitIt.tga", "done.tga", "DragonAww.tga", "DragonCozy.tga", "DragonCry.tga", "DragonFat.tga",
      "DragonREE.tga", "DragonSip.tga", "DragonThink.tga", "DragonWave.tga", "duckieW.tga", "ehWTF.tga",
      "ELE.tga", "emDface.tga", "eShrug.tga", "espanLOL.tga", "EVILSMILERS.tga", "ExitG.tga",
      "EZ.tga", "EZChamp.tga", "FapFapFap.tga", "FARTIUM.tga", "FatBod.tga", "FatCat.tga",
      "FatDank.tga", "Fatge.tga", "FeelsAllianceMan.tga", "FeelsAmazingMan.tga", "FeelsBadMan.tga", "FeelsBadManF.tga",
      "FeelsBadManV.tga", "FeelsBadW.tga", "FeelsBetaMan.tga", "FeelsBirthdayMan.tga", "feelsblob.tga", "FeelsBlushMan.tga",
      "FeelsBoomieMan.tga", "FeelsBoredMan.tga", "FeelsComradeMan.tga", "FeelsCoolMan.tga", "FeelsCopterMan.tga", "FeelsCringeMan.tga",
      "FeelsCryMan.tga", "FeelsCuteMan.tga", "FeelsDabMan.tga", "FeelsDeadMan.tga", "FeelsDorkMan.tga", "FeelsDrunkMan.tga",
      "FeelsDutchMan.tga", "FeelsEleMan.tga", "FeelsEvilMan.tga", "FeelsFatMan.tga", "FeelsGamerMan.tga", "FeelsGermanMan.tga",
      "FeelsGoodEnoughMan.tga", "FeelsGoodMan.tga", "FeelsGreatMan.tga", "FeelsGreekMan.tga", "FeelsHordeMan.tga", "FeelsHug.tga",
      "FeelsHugged.tga", "FeelsHunterMan.tga", "FeelsIncredibleMan.tga", "FeelsLitMan.tga", "FeelsLoveManW.tga", "FeelsMyFingerMan.tga",
      "FeelsNewYear.tga", "FeelsOakyMan.tga", "FeelsOkayMan.tga", "FeelsOldMan.tga", "FeelsPinkMan.tga", "FeelsPumpkinMan.tga",
      "FeelsRainSadge.tga", "FeelsRottenMan.tga", "FeelsSad.tga", "FeelsSadMan.tga", "FeelsShadowMan.tga", "FeelsSleepyMan.tga",
      "FeelsSnowMan.tga", "FeelsSnowyMan.tga", "FeelsSorryMan.tga", "FeelsStrongMan.tga", "FeelsSuicideMan.tga", "FeelsTankMan.tga",
      "FeelsTastyMan.tga", "FeelsThinkingMan.tga", "FeelsTired.tga", "FeelsTiredAF.tga", "FeelsUnsureMan.tga", "FeelsWeirdMan.tga",
      "FeelsWiredMan.tga", "FeelsWowMan.tga", "fingi.tga", "FishMoley.tga", "FLOPPERS.tga", "fml.tga",
      "ForeverAlone.tga", "FrogO.tga", "Frostbitchyes.tga", "FUARK.tga", "FuckYea.tga", "GabeN.tga",
      "gachiGASM.tga", "Gayge.tga", "Gerdlerk1.tga", "Gerdlerk2.tga", "Gerdlerk3.tga", "Gerdlerk4.tga",
      "GiggleHands.tga", "GIMMIE.tga", "Gladge.tga", "gladgers.tga", "goodd.tga", "GoodW.tga",
      "greekDitch.tga", "greekLOUDER.tga", "guna.tga", "gXD.tga", "HabibiPrayge.tga", "HACKERMANS.tga",
      "HammersArk.tga", "HammersNoArk.tga", "HammerTime.tga", "HandsUp.tga", "HappyJammies.tga", "Heartato.tga",
      "HerbPerve.tga", "Hhhehehe.tga", "HmmChamp.tga", "Hmmge.tga", "Hmmmge.tga", "hoboW.tga",
      "HomieL.tga", "HomieR.tga", "HYPERBRUH.tga", "HYPERDANSGAME.tga", "HYPERDANSGAMEW.tga", "HYPEROMEGALUL.tga",
      "HYPEROMEGAPOGGERSCRAZY.tga", "HYPERS.tga", "HYPERTHONK.tga", "imKEKWing.tga", "imOkayChamp.tga", "InspectorAngryWoof.tga",
      "InspectorAngryWoofM.tga", "JanCarlo.tga", "jerryWhat.tga", "Joy2.tga", "Joy3.tga", "just.tga",
      "Kaged.tga", "Kapp.tga", "KEKE.tga", "KekeHands.tga", "KEKGA.tga", "KEKL.tga",
      "KEKLeo.tga", "KEKPog.tga", "KEKpoint.tga", "KEKSad.tga", "kekW.tga", "KEKWeird.tga",
      "KEKWHands.tga", "KEKWPog.tga", "Kermitpls.tga", "KKomrade.tga", "KKona.tga", "KKonaW.tga",
      "KKonductor.tga", "KKool.tga", "Krappa.tga", "LaughW.tga", "lethink.tga", "LilZ.tga",
      "LMAO.tga", "lookdown.tga", "lookup.tga", "Lovepeepo.tga", "Lovge.tga", "LUL.tga",
      "LULChamp.tga", "LULE.tga", "LULERS.tga", "LULW.tga", "LULWW.tga", "Lyeasy.tga",
      "LyeCute.tga", "LyeREE.tga", "LyeShrug.tga", "LyEZ.tga", "Madge.tga", "MadgeBackhand.tga",
      "MadgeClap.tga", "Madgee.tga", "MadgeNow.tga", "MadgeRightNow.tga", "majj.tga", "MaldChamp.tga",
      "MALDD.tga", "MamaMiaItaliano.tga", "MaN.tga", "maximumautism.tga", "Maya.tga", "meAutism.tga",
      "MEGALUL.tga", "MEGALUL_2.tga", "memebeam1.tga", "memebeam2.tga", "memebeam3.tga", "MingLuL.tga",
      "monakGun.tga", "monakHmm.tga", "Monaks1.tga", "monakW.tga", "monkaANELE.tga", "monkaBlanket.tga",
      "monkaCapture.tga", "monkaChrist.tga", "monkaD.tga", "monkaEyes.tga", "monkaGasp.tga", "monkaGIGA.tga",
      "monkaGun.tga", "monkaH.tga", "monkaHands.tga", "monkaHmm.tga", "monkaJail.tga", "monkaKek.tga",
      "monkaLaugh.tga", "monkaMEGA.tga", "monkaOh.tga", "monkaOMEGA.tga", "monkaPickle.tga", "monkaS.tga",
      "Monkas1.tga", "monkaShake.tga", "monkaStab.tga", "monkaStare.tga", "monkaStop.tga", "monkaSusp.tga",
      "monkaT.tga", "monkaThink.tga", "monkaTOS.tga", "monkaU.tga", "monkaVirus.tga", "monkaW.tga",
      "monkaWCB.tga", "monkaYou.tga", "monkerS.tga", "NA.tga", "NaM.tga", "nanoMEGA.tga",
      "NeckBeard.tga", "needcopium.tga", "NeedCopiumPepe.tga", "needdrama.tga", "needmemes1.tga", "needmemes2.tga",
      "Nerdge.tga", "NickyQ.tga", "noClown.tga", "NOOBA.tga", "NOP.tga", "NotLike.tga",
      "Notsurege.tga", "noxSorry.tga", "noxWhat.tga", "OhISee.tga", "OhYouSee.tga", "OkayChamp.tga",
      "OkayChomp.tga", "Okayeg.tga", "Okayga.tga", "Okayge.tga", "OkaygeShrug.tga", "OkayLaugh.tga",
      "OkayW.tga", "OldChamp.tga", "oldpepe.tga", "OMEGAEZ.tga", "OMEGAKEKW.tga", "OMEGALUL.tga",
      "OMEGASP.tga", "OMEGATriHard.tga", "oniongang.tga", "oof.tga", "PagChomp.tga", "PagMan.tga",
      "PainsChamp.tga", "PantsGrab.tga", "PATHETIC.tga", "PauseChamp.tga", "PAUSERS.tga", "Pausey.tga",
      "PBear.tga", "peep.tga", "peepaGrown.tga", "peepaKiss.tga", "peepaSexy.tga", "PeepGiggle.tga",
      "PeepHand.tga", "PeepKek.tga", "PeepLaugh.tga", "peepoAlliance.tga", "peepoAP.tga", "peepoBaba.tga",
      "peepoBeer.tga", "peepoBlankey.tga", "peepoBlush.tga", "peepoBlushing.tga", "peepoBored.tga", "peepoBritish.tga",
      "peepoBye.tga", "peepoCharge.tga", "peepoCheer.tga", "peepoChonk.tga", "peepoClap.tga", "peepoCN.tga",
      "peepoCringe.tga", "peepoCrown.tga", "peepoCute.tga", "peepoDab.tga", "peepoDE.tga", "peepoDetective.tga",
      "peepoDetective2.tga", "peepoES.tga", "peepoEU.tga", "peepoEvilSip.tga", "peepoExit.tga", "peepoEyes.tga",
      "peepoEZ.tga", "peepoFA.tga", "peepoFat.tga", "peepoFH.tga", "peepoFight.tga", "peepoFoil.tga",
      "peepoFR1.tga", "peepoFR2.tga", "peepoFriends.tga", "peepoFrogHappy.tga", "peepoGift.tga", "peepoGlad.tga",
      "peepoGun.tga", "peepoH.tga", "peepoHands.tga", "peepoHeart.tga", "peepoHeHe.tga", "peepoHey.tga",
      "peepoHide.tga", "peepoHmm.tga", "peepoHug.tga", "peepoHugged.tga", "peepoHuggiesL.tga", "peepoHuggiesR.tga",
      "peepoIgnore.tga", "peepoIsForMe.tga", "peepoJail.tga", "peepoJammies.tga", "peepoJedi.tga", "peepoJorts.tga",
      "peepoJudge.tga", "peepoJuice.tga", "peepOK.tga", "peepoKEKW.tga", "peepoKing.tga", "peepoKiss.tga",
      "peepoKnight.tga", "peepoLip.tga", "peepoLoser.tga", "peepoLove.tga", "peepoM.tga", "peepoMadder.tga",
      "peepoMaybe.tga", "peepoNice.tga", "peepoNo.tga", "peepoNolegs.tga", "peepoNOO.tga", "peepoNOOO.tga",
      "peepoNotes.tga", "peepoOK.tga", "peepoPanda.tga", "peepoPants.tga", "peepoParty.tga", "peepoPee.tga",
      "peepoPeek.tga", "peepoPing.tga", "peepoPlease.tga", "peepoPlot.tga", "peepoPogPoo.tga", "peepoPoint.tga",
      "peepoPoo.tga", "peepoPopcorn.tga", "peepoPride.tga", "peepoRain.tga", "peepoReallyHappy.tga", "peepoS.tga",
      "peepoSadCat.tga", "peepoSadLogize.tga", "peepoSalute.tga", "peepoScam.tga", "peepoSE.tga", "peepoSenor.tga",
      "peepoShower.tga", "peepoShrug.tga", "peepoShy.tga", "peepoSick.tga", "peepoSimp.tga", "peepoSimping.tga",
      "peepoSip.tga", "peepoSith.tga", "peepoSleepo.tga", "peepoSmile.tga", "peepoSoup.tga", "peepoSPopcorn.tga",
      "peepoStab.tga", "peepoStonks.tga", "peepoStudy.tga", "peepoSure.tga", "peepoSuspect.tga", "peepoSuspicious.tga",
      "peepoSweat.tga", "peepoTeddy.tga", "peepoTeeth.tga", "peepoThink.tga", "peepoTip.tga", "peepoTired.tga",
      "peepoTrash.tga", "peepoUgh.tga", "peepoUK.tga", "peepoUSA.tga", "peepoWave.tga", "peepoWeird.tga",
      "peepoWeirdCrown.tga", "peepoWhy.tga", "peepoWoW.tga", "peepoWTF.tga", "PepeAyy.tga", "PepeBean.tga",
      "pepeBlyat.tga", "pepeBruh.tga", "PepeButt.tga", "PepeCat.tga", "PepeCatGun.tga", "PepeCatHeart.tga",
      "PepeCoffee.tga", "PepeCoolStory.tga", "PepeCozy.tga", "PepeDent.tga", "PepeDisgust.tga", "PepeDribble.tga",
      "PepeFeet.tga", "PepeFinger.tga", "PepeFist.tga", "PepeFlushed.tga", "PepeFork.tga", "PepeFrench.tga",
      "PepeFU.tga", "PepeFuming.tga", "PepeG.tga", "Pepega.tga", "PepegaHammer.tga", "PepegaHands.tga",
      "PepegaKMS.tga", "PepegaLaugh.tga", "PepeGamer.tga", "pepeGang.tga", "PepegaPoo.tga", "PepegaS.tga",
      "PepegaSad.tga", "Pepege.tga", "PepegeS.tga", "PepegeSit.tga", "PepegeWeird.tga", "Pepeggers.tga",
      "Pepegwa.tga", "pepeHam.tga", "PepeHands.tga", "PepeHard.tga", "PepeHeart.tga", "PepeHug.tga",
      "PepeIgnore.tga", "PepeKMS.tga", "PepeL.tga", "PepeLa.tga", "PepeLaffe.tga", "PepeLaugh.tga",
      "PepeLegs.tga", "PepeLMAO.tga", "PepeLoser.tga", "PepeLove.tga", "PepeM.tga", "PepeManos.tga",
      "PepeMegaSad.tga", "PepeMods.tga", "PepeMStache.tga", "PepeNo.tga", "pepeNotOK.tga", "pepeOK.tga",
      "PepeOuuuhh.tga", "Pepepains.tga", "PepePants.tga", "PepePhone.tga", "PepePhoned.tga", "PepePlan.tga",
      "PepePoint.tga", "PepePoo.tga", "PepePopcorn.tga", "PePeppaPig.tga", "PepePuke.tga", "PepePyroblast.tga",
      "PepeReach.tga", "PepeRun.tga", "PepeScoots.tga", "PepeScout.tga", "PepeSlice.tga", "PepeSmile.tga",
      "PepeSmoke.tga", "pepeStepBro.tga", "PepeStressed.tga", "PepeTHICC.tga", "PepeThumbsUp.tga", "PepeUnicorn.tga",
      "pepeW.tga", "PepeWhip.tga", "PepeWizard.tga", "PepeWot.tga", "PepeXD.tga", "PepeYes.tga",
      "pepoEZ.tga", "pepoGun.tga", "pepohide.tga", "PepOMEGA.tga", "pepoS.tga", "pepoScience.tga",
      "PepoThink.tga", "PepperHands.tga", "Pho.tga", "PikaWOW.tga", "pillowJammies.tga", "Pog.tga",
      "pOg1.tga", "PogClappa.tga", "Pogey.tga", "PogeyU.tga", "pogg.tga", "POGGAROO.tga",
      "POGGERS.tga", "POGGERSF.tga", "PoggersHype.tga", "PoggersHypeF.tga", "POGGERSLove.tga", "Poghurt.tga",
      "PogMe.tga", "PogO.tga", "PogO2.tga", "PogOff.tga", "Pogomega.tga", "PogOW.tga",
      "PogU.tga", "PogWarts.tga", "PogYou.tga", "POOGERS.tga", "PotFriend.tga", "PowerUpL.tga",
      "PowerUpR.tga", "PPepoCool.tga", "PPepoHit.tga", "ppEZ.tga", "ppFootbol.tga", "PPirate.tga",
      "ppSmoke.tga", "PraiseTheSun.tga", "Prayge.tga", "RandomPepe.tga", "Ratge.tga", "Readge.tga",
      "REEE.tga", "Riotge.tga", "RowFish.tga", "RowSalt.tga", "SadBlanket.tga", "SadCash.tga",
      "SadCatWave.tga", "SadChamp.tga", "Sadga.tga", "sadgers.tga", "SadHonk.tga", "sadhug.tga",
      "SadJAM.tga", "SadLove.tga", "SadOke.tga", "SadPepe.tga", "SAJ.tga", "sajj.tga",
      "SaladPepega.tga", "salutt.tga", "savixHappy.tga", "SchubertaBruh.tga", "SchubertBruh.tga", "SchubertSmile.tga",
      "shrujj.tga", "shy.tga", "SillyChamp.tga", "Sk.tga", "SkDead.tga", "SkEvil.tga",
      "SkGasm.tga", "skip.tga", "SkMad.tga", "SkNervous.tga", "SkSad.tga", "SkSmile.tga",
      "SkSpook.tga", "SkWeird.tga", "SkWink.tga", "Smadge.tga", "SmileHard.tga", "Smilers.tga",
      "Smoge.tga", "SMUGGERS.tga", "SmugPepe.tga", "sosig.tga", "sosigW.tga", "soupchamp.tga",
      "spit1.tga", "spit2.tga", "squawk.tga", "stabby.tga", "StareBruh.tga", "StareChamp.tga",
      "Starege.tga", "Stronge.tga", "SucksMan.tga", "Susge.tga", "Suske.tga", "thehmm.tga",
      "thethink.tga", "Thonk.tga", "ThrallS.tga", "tip.tga", "TiredW.tga", "tomatogang.tga",
      "tooDank.tga", "TOSga.tga", "trash.tga", "TriEasy.tga", "TriGold.tga", "TriHardS.tga",
      "TriKool.tga", "TriPeek.tga", "TriTasty.tga", "TroggHYPERS.tga", "UHM.tga", "VaN.tga",
      "VapeNation.tga", "Voidge.tga", "wardog.tga", "WeirdBruh.tga", "WeirdChamp.tga", "WeirdChampion.tga",
      "Weirders.tga", "Weirdga.tga", "Weirdge.tga", "WeirdJAM.tga", "WeirdU.tga", "WeirdW.tga",
      "welp.tga", "weSmart.tga", "WhiteKnight.tga", "WickedDrip.tga", "Wipege.tga", "WOAW.tga",
      "Wokege.tga", "Wokegesus.tga", "Wowee.tga", "WULL.tga", "WutChamp.tga", "YAMERO.tga",
      "YEP.tga", "Yepge.tga", "YIKERS.tga", "YUM.tga", "ZFeral.tga", "ZkkOna.tga",
      "ZOINKS.tga", "Zoomer.tga", "ZShelia.tga", "ZULOL.tga", "ZULUL.tga", "zxEpic.tga",
      "zxGary.tga", "ZXSaiko.tga",
    },
    },
    { name = "FojjiCore", root = FOJJI_ROOT, addon = "FojjiCore", path = "", files = {
      "arcane_missiles.blp", "arcane_missiles_1.blp", "arcane_missiles_2.blp", "arcane_missiles_3.blp", "art_of_war.blp", "Back_1_Overlay.png",
      "Back_2_Overlay.png", "backlash.blp", "backlash_green.blp", "bandits_guile.blp", "Bashful.blp", "berserk.blp",
      "Berserk.tga", "blood_boil.blp", "Blood_Boil.tga", "blood_surge.blp", "Bowling.blp", "brain_freeze.blp",
      "BRAIN_FREEZE2.BLP", "cast_shield.tga", "dark_tiger.blp", "dark_transformation.blp", "daybreak.blp", "demonic_core.blp",
      "demonic_core_vertical.blp", "denounce.blp", "discicon_nuHorde_v3anim.tga", "discicon_nuHordev2.tga", "discordicon_NuAnim2_horde.tga", "echo_of_the_elements.blp",
      "eclipse_moon.blp", "eclipse_sun.blp", "F_icon_green.blp", "F_icon_orange.blp", "F_icon_purple.blp", "F_icon_teal.png",
      "F_icon_yellow.blp", "feral_omenofclarity.blp", "focus_fire.blp", "FojjiBlue.tga", "FojjiRed.tga", "FROZEN_FINGERS.BLP",
      "fulmination.blp", "fury_of_stormrage.blp", "genericarc_01.blp", "genericarc_02.blp", "genericarc_03.blp", "genericarc_04.blp",
      "genericarc_05.blp", "genericarc_06.blp", "generictop_01.blp", "generictop_02.blp", "grand_crusader.blp", "hand_of_light.blp",
      "high_tide.blp", "HOT_STREAK.BLP", "imp_empowerment.blp", "imp_empowerment_green.blp", "impact.blp", "JoardeeKid.blp",
      "JoardePog.blp", "killing_machine.blp", "Left_1_Overlay.png", "Left_2_Overlay.png", "Lightsaber.tga", "lock_and_load.blp",
      "maelstrom_weapon.blp", "maelstrom_weapon_1.blp", "maelstrom_weapon_2.blp", "maelstrom_weapon_3.blp", "maelstrom_weapon_4.blp", "MarioCoin.tga",
      "mask.blp", "maskzero.blp", "master_marksman.blp", "molten_core.blp", "molten_core_green.blp", "monk_blackoutkick.blp",
      "monk_ox.blp", "monk_ox_2.blp", "monk_ox_3.blp", "monk_serpent.blp", "monk_tiger.blp", "monk_tigerpalm.blp",
      "natures_grace.blp", "necropolis.blp", "nightfall.blp", "nuLogo_Alliance.tga", "nuMOP_Gold_v2.png", "nuMOP_Green.png",
      "nuMOP_Sha_Green256.png", "nyan.tga", "OLDEclipse_Moon.tga", "OLDEclipse_Sun.tga", "predatory_swiftness.blp", "predatory_swiftness_green.blp",
      "raging_blow.blp", "Right_1_Overlay.png", "Right_2_Overlay.png", "rime.blp", "serendipity.blp", "shadow_of_death.blp",
      "shadow_word_insanity.blp", "ShaPagoda.png", "shooting_stars.blp", "slice_and_dice.blp", "SombreroHat.tga", "SonicRing.blp",
      "spellactivationoverlay_0.blp", "sudden_death.blp", "sudden_death_red.tga", "sudden_doom.blp", "surge_of_darkness.blp", "surge_of_light.blp",
      "sword_and_board.blp", "t_star3.blp", "Terrorists.blp", "Tetsuhands.blp", "TetsuPog.blp", "thrill_of_the_hunt_1.blp",
      "thrill_of_the_hunt_2.blp", "thrill_of_the_hunt_3.blp", "tooth_and_claw.blp", "ultimatum.blp", "Weapon_c4.blp", "white_tiger.blp",
    },
    },
    { name = "FojjiCore: BTTV+FFZ", root = FOJJI_ROOT, addon = "FojjiCore", path = "BTTV+FFZ\\", files = {
      "4HEad.tga", "BBona.tga", "bUrself.tga", "ChogPamp.tga", "CiGrip.tga", "ConcernDoge.tga",
      "DogeWitIt.tga", "emDface.tga", "eShrug.tga", "FapFapFap.tga", "FishMoley.tga", "ForeverAlone.tga",
      "FuckYea.tga", "GabeN.tga", "gachiBASS.tga", "gachiGASM.tga", "haHAA.tga", "HammerTime.tga",
      "HandsUp.tga", "HerbPerve.tga", "Hhhehehe.tga", "HYPERBRUH.tga", "HYPERTHONK.tga", "Kaged.tga",
      "Kapp.tga", "Kermitpls.tga", "KKomrade.tga", "KKona.tga", "Krappa.tga", "LilZ.tga",
      "LUL.tga", "LULE.tga", "LULW.tga", "MEGALUL.tga", "MingLuL.tga", "NickyQ.tga",
      "NotLike.tga", "OMEGALUL.tga", "PagChomp.tga", "PagMan.tga", "PauseChamp.tga", "pokiBASS.tga",
      "PotFriend.tga", "PowerUpL.tga", "PowerUpR.tga", "Thonk.tga", "tooDank.tga", "VapeNation.tga",
      "weSmart.tga", "Wowee.tga", "ZULOL.tga", "ZULUL.tga",
    },
    },
    { name = "FojjiCore: DungeonJournal", root = FOJJI_ROOT, addon = "FojjiCore", path = "DungeonJournal\\", files = {
      "mark-aoe.tga", "mark-arrow.tga", "mark-chest.tga", "mark-cross.tga", "mark-door.tga", "mark-eye.tga",
      "mark-finish.tga", "mark-flag.tga", "mark-heal.tga", "mark-patrol.tga", "mark-question.tga", "mark-shield.tga",
      "mark-skull.tga", "mark-sleep.tga", "mark-stairs.tga", "mark-star.tga", "mark-swords.tga", "mark-warn.tga",
      "ui-book.tga", "ui-brush.tga", "ui-close.tga", "ui-cursor.tga", "ui-dot.tga", "ui-eraser.tga",
      "ui-expand.tga", "ui-grip.tga", "ui-layers.tga", "ui-party.tga", "ui-pin.tga", "ui-questlog.tga",
      "ui-ring.tga", "ui-route.tga", "ui-stamp.tga", "ui-trash.tga", "ui-undo.tga", "ui-waypoint.tga",
      "ui-wowpin.tga",
    },
    },
    { name = "FojjiCore: DungeonMaps", root = FOJJI_ROOT, addon = "FojjiCore", path = "DungeonMaps\\", files = {
      "Dalaran1.tga", "Dalaran2.tga", "Excavation1.tga",
    },
    },
    { name = "FojjiCore: FojjiIcons", root = FOJJI_ROOT, addon = "FojjiCore", path = "FojjiIcons\\", files = {
      "F_icon_blue.png", "F_icon_brown.png", "F_icon_green.png", "F_icon_lightblue.png", "F_icon_lightblue.tga", "F_icon_minimap.tga",
      "F_icon_orange.png", "F_icon_purple.png", "F_icon_red.png", "F_icon_teal.png", "F_icon_yellow.png", "F_logo_arc.tga",
      "F_logo_arc_64.tga", "F_logo_base.tga", "F_logo_base_64.tga", "Fojji_Banner_Blue.png", "Fojji_Banner_Red.png", "Fojji_Blue.png",
      "Fojji_F.png", "Fojji_Forever.png", "Fojji_Forever_128.tga", "Fojji_Red.png", "Fojji_YTB.png", "fojjiHEART.png",
      "fojjiLuL.png", "fojjiMEOW.png", "fojjiSIP.png", "ForeverAuras.png", "ForeverAuras_128.tga", "nuLogo_GOLD.png",
      "nuLogo_GOLDRED.png", "nuLogo_GREEN.png", "nuLogo_LIGHTBLUE.png", "nuLogo_MOPGOLD.png", "nuLogo_RED.png", "nuLogo_REDORANGE.png",
      "nuLogo_SHAGREEN.png", "nuLogo_WHITE.png",
    },
    },
    { name = "FojjiCore: GuildEmotes", root = FOJJI_ROOT, addon = "FojjiCore", path = "GuildEmotes\\", files = {
      "0Head.tga", "1Head.tga", "2Head.tga", "3Head.tga", "3Lass.tga", "4HEader.tga",
      "4House.tga", "4Mansion.tga", "4Shrug.tga", "4Town.tga", "4Weird.tga", "4WeirdW.tga",
      "5Champ.tga", "5Hard.tga", "5Head.tga", "AMAZINGA.tga", "ANGERY.tga", "AngeryCry.tga",
      "Angy.tga", "asmonPower.tga", "AYAYARR.tga", "AYAYAWeird.tga", "BaconEffect.tga", "BearDab.tga",
      "BigNars.tga", "BinCat.tga", "BlackKnight.tga", "BOGGED.tga", "Boomer.tga", "Breadclown.tga",
      "Britpega.tga", "BroKiss.tga", "Bwonsambee.tga", "CatChest.tga", "ChagU.tga", "CHAMPERS.tga",
      "ChampU.tga", "checkdoggo.tga", "Chomp.tga", "CloakofShadows.tga", "cmoB.tga", "cmoN1.tga",
      "cmonBruv.tga", "cmonEyes.tga", "cmoV.tga", "Coomer.tga", "CrazyChamp.tga", "danebrain.tga",
      "deadgemines.tga", "DidntAsk.tga", "DisappointChamp.tga", "DKKona.tga", "DogeKek.tga", "DragonAww.tga",
      "DragonCozy.tga", "DragonCry.tga", "DragonFat.tga", "DragonREE.tga", "DragonSip.tga", "DragonThink.tga",
      "DragonWave.tga", "duckieW.tga", "ELE.tga", "espanLOL.tga", "ExitG.tga", "EZChamp.tga",
      "FatCat.tga", "feelsblob.tga", "FeelsTankMan.tga", "FLOPPERS.tga", "Frostbitchyes.tga", "Gerdlerk1.tga",
      "Gerdlerk2.tga", "Gerdlerk3.tga", "Gerdlerk4.tga", "guna.tga", "gXD.tga", "HammersArk.tga",
      "HammersNoArk.tga", "Heartato.tga", "HmmChamp.tga", "hoboW.tga", "HomieL.tga", "HomieR.tga",
      "HYPERDANSGAME.tga", "HYPERDANSGAMEW.tga", "HYPEROMEGALUL.tga", "InspectorAngryWoof.tga", "InspectorAngryWoofM.tga", "jerryWhat.tga",
      "Joy2.tga", "Joy3.tga", "just.tga", "KEKE.tga", "KEKL.tga", "KEKLeo.tga",
      "KEKPog.tga", "KEKpoint.tga", "KEKSad.tga", "kekW.tga", "KEKWeird.tga", "KEKWPog.tga",
      "KKonaW.tga", "KKonductor.tga", "KKool.tga", "lethink.tga", "LULChamp.tga", "LULWW.tga",
      "Lyeasy.tga", "LyeCute.tga", "LyeREE.tga", "LyeShrug.tga", "LyEZ.tga", "MaldChamp.tga",
      "MamaMiaItaliano.tga", "MaN.tga", "Maya.tga", "NaM.tga", "NeckBeard.tga", "noxSorry.tga",
      "noxWhat.tga", "OhISee.tga", "OhYouSee.tga", "OkayChamp.tga", "OkayChomp.tga", "OldChamp.tga",
      "OMEGAKEKW.tga", "OMEGASP.tga", "OMEGATriHard.tga", "oof.tga", "PainsChamp.tga", "PantsGrab.tga",
      "PATHETIC.tga", "Pausey.tga", "PBear.tga", "PeepoPog.tga", "Pho.tga", "PikaWOW.tga",
      "Pog.tga", "pOg1.tga", "PogClappa.tga", "Pogey.tga", "PogeyU.tga", "POGGAROO.tga",
      "Poghurt.tga", "PogMe.tga", "PogO.tga", "PogOff.tga", "Pogomega.tga", "PogOW.tga",
      "PogTasty.tga", "PogU.tga", "PogWarts.tga", "PogYou.tga", "PPirate.tga", "PraiseTheSun.tga",
      "RowFish.tga", "RowSalt.tga", "SadCash.tga", "SadCatWave.tga", "SadChamp.tga", "SadOke.tga",
      "SaladPepega.tga", "savixHappy.tga", "SillyChamp.tga", "Sk.tga", "SkDead.tga", "SkEvil.tga",
      "SkGasm.tga", "SkMad.tga", "SkNervous.tga", "SkSad.tga", "SkSmile.tga", "SkSpook.tga",
      "SkWeird.tga", "SkWink.tga", "SmileHard.tga", "sosig.tga", "sosigW.tga", "squawk.tga",
      "stabby.tga", "StareBruh.tga", "StareChamp.tga", "ThrallS.tga", "tip.tga", "trash.tga",
      "TriEasy.tga", "TriGold.tga", "TriHardo.tga", "TriHardS.tga", "TriKool.tga", "TriPeek.tga",
      "TriTasty.tga", "VaN.tga", "wardog.tga", "WeirdBruh.tga", "WeirdChamp.tga", "WeirdChampion.tga",
      "welp.tga", "WhiteKnight.tga", "WULL.tga", "WutChamp.tga", "YAMERO.tga", "YUM.tga",
      "ZFeral.tga", "ZkkOna.tga", "ZOINKS.tga", "Zoomer.tga", "ZShelia.tga", "zxEpic.tga",
      "zxGary.tga", "ZXSaiko.tga",
    },
    },
    { name = "FojjiCore: Karazhan", root = FOJJI_ROOT, addon = "FojjiCore", path = "Karazhan\\", files = {
      "bigbadwolf.png", "crone.png", "redridinghood.png", "roar.png", "romeoandjuliet.png", "strawman.png",
      "tinhead.png", "toto.png", "wizardofoz.png",
    },
    },
    { name = "FojjiCore: MemeArt", root = FOJJI_ROOT, addon = "FojjiCore", path = "MemeArt\\", files = {
      "JurassicPark.png", "JurassicParkFull.png",
    },
    },
    { name = "FojjiCore: Naxx Pack Icons", root = FOJJI_ROOT, addon = "FojjiCore", path = "Naxx Pack Icons\\", files = {
      "1107-icon.tga", "1108-icon.tga", "1109-icon.tga", "1110-icon.tga", "1111-icon.tga", "1112-icon.tga",
      "1113-icon.tga", "1114-icon.tga", "1115-icon.tga", "1116-icon.tga", "1117-icon.tga", "1118-icon.tga",
      "1119-icon.tga", "1120-icon.tga", "1121-icon.tga",
    },
    },
    { name = "FojjiCore: Pepes", root = FOJJI_ROOT, addon = "FojjiCore", path = "Pepes\\", files = {
      "4peepo.tga", "Awakge.tga", "Bedge.tga", "Bedges.tga", "BedgeTogether.tga", "binocs.tga",
      "binocsSpin.tga", "BLUBBERS.tga", "Blushge.tga", "BOOBA.tga", "BOOFA.tga", "Boolin.tga",
      "Borpa.tga", "BorpaL.tga", "BorpaU.tga", "Catge.tga", "Chatting.tga", "ClownBall.tga",
      "Clownge.tga", "ClownHypers.tga", "ClownPain.tga", "COCKA.tga", "COGGERS.tga", "Copege.tga",
      "COPIUM.tga", "coronaS.tga", "CringeW.tga", "CROGGERS.tga", "Cryge.tga", "CutePepe.tga",
      "DankHug.tga", "Deadge.tga", "DeadgeTogether.tga", "dejj.tga", "Despairge.tga", "DIDSOMEONESAYCOCK.tga",
      "DinkDonk.tga", "done.tga", "ehWTF.tga", "EVILSMILERS.tga", "EZ.tga", "FARTIUM.tga",
      "FatBod.tga", "FatDank.tga", "Fatge.tga", "FeelsAllianceMan.tga", "FeelsAmazingMan.tga", "FeelsBadMan.tga",
      "FeelsBadManF.tga", "FeelsBadManV.tga", "FeelsBadW.tga", "FeelsBetaMan.tga", "FeelsBirthdayMan.tga", "FeelsBlushMan.tga",
      "FeelsBoomieMan.tga", "FeelsBoredMan.tga", "FeelsComradeMan.tga", "FeelsCoolMan.tga", "FeelsCopterMan.tga", "FeelsCringeMan.tga",
      "FeelsCryMan.tga", "FeelsCuteMan.tga", "FeelsDabMan.tga", "FeelsDeadMan.tga", "FeelsDorkMan.tga", "FeelsDrunkMan.tga",
      "FeelsDutchMan.tga", "FeelsEleMan.tga", "FeelsEvilMan.tga", "FeelsFatMan.tga", "FeelsGamerMan.tga", "FeelsGermanMan.tga",
      "FeelsGoodEnoughMan.tga", "FeelsGoodMan.tga", "FeelsGreatMan.tga", "FeelsGreekMan.tga", "FeelsHordeMan.tga", "FeelsHug.tga",
      "FeelsHugged.tga", "FeelsHunterMan.tga", "FeelsIllidanMan.tga", "FeelsIncredibleMan.tga", "FeelsLateMan.tga", "FeelsLitMan.tga",
      "FeelsLoveMan.tga", "FeelsLoveManW.tga", "FeelsMyFingerMan.tga", "FeelsNewYear.tga", "FeelsNzoth.tga", "FeelsOakyMan.tga",
      "FeelsOkayMan.tga", "FeelsOldMan.tga", "FeelsPinkMan.tga", "FeelsPumpkinMan.tga", "FeelsQueueMan.tga", "FeelsRainMan.tga",
      "FeelsRainSadge.tga", "FeelsRottenMan.tga", "FeelsSad.tga", "FeelsSadMan.tga", "FeelsShadowMan.tga", "FeelsSleepyMan.tga",
      "FeelsSnowMan.tga", "FeelsSnowyMan.tga", "FeelsSorryMan.tga", "FeelsStrongMan.tga", "FeelsSuicideMan.tga", "FeelsTastyMan.tga",
      "FeelsThinkingMan.tga", "FeelsTired.tga", "FeelsTiredAF.tga", "FeelsUnsureMan.tga", "FeelsWeakMan.tga", "FeelsWeirdMan.tga",
      "FeelsWiredMan.tga", "FeelsWowMan.tga", "fingi.tga", "fml.tga", "FrogO.tga", "FUARK.tga",
      "FUTA.tga", "Gayge.tga", "GiggleHands.tga", "GIMMIE.tga", "Gladge.tga", "gladgers.tga",
      "goodd.tga", "GoodW.tga", "greekDitch.tga", "greekLOUDER.tga", "HabibiPrayge.tga", "HACKERMANS.tga",
      "HappyJammies.tga", "Hmmge.tga", "Hmmmge.tga", "HYPEROMEGAPOGGERSCRAZY.tga", "HYPERS.tga", "imKEKWing.tga",
      "imOkayChamp.tga", "Jammies.tga", "JanCarlo.tga", "KekeHands.tga", "KEKGA.tga", "KEKWHands.tga",
      "LaughW.tga", "LMAO.tga", "lookdown.tga", "lookup.tga", "lovehug.tga", "Lovepeepo.tga",
      "Lovge.tga", "LULERS.tga", "Madge.tga", "MadgeBackhand.tga", "MadgeClap.tga", "Madgee.tga",
      "MadgeNow.tga", "MadgeRightNow.tga", "majj.tga", "MALDD.tga", "maximumautism.tga", "meAutism.tga",
      "MEGALUL.tga", "memebeam1.tga", "memebeam2.tga", "memebeam3.tga", "monakGun.tga", "monakHmm.tga",
      "Monaks1.tga", "monakW.tga", "monkaANELE.tga", "monkaBlanket.tga", "monkaCapture.tga", "monkaChrist.tga",
      "monkaD.tga", "monkaEyes.tga", "monkaGasp.tga", "monkaGIGA.tga", "monkaGun.tga", "monkaH.tga",
      "monkaHands.tga", "monkaHmm.tga", "monkaInsane.tga", "monkaJail.tga", "monkaKek.tga", "monkaLaugh.tga",
      "monkaMEGA.tga", "monkaOh.tga", "monkaOMEGA.tga", "monkaPickle.tga", "monkaS.tga", "Monkas1.tga",
      "monkaShake.tga", "monkaShoot.tga", "monkaStab.tga", "monkaStare.tga", "monkaSteer.tga", "monkaStop.tga",
      "monkaSusp.tga", "monkaT.tga", "monkaThink.tga", "monkaTOS.tga", "monkaU.tga", "monkaVirus.tga",
      "monkaW.tga", "monkaWCB.tga", "monkaX.tga", "monkaYou.tga", "monkerS.tga", "NA.tga",
      "nanoMEGA.tga", "needcopium.tga", "NeedCopiumPepe.tga", "needdrama.tga", "needmemes1.tga", "needmemes2.tga",
      "Nerdge.tga", "noClown.tga", "NODDERS.tga", "NOOBA.tga", "NOP.tga", "NOPERS.tga",
      "Notsurege.tga", "Okayeg.tga", "Okayga.tga", "Okayge.tga", "OkaygeShrug.tga", "OkayLaugh.tga",
      "OkayW.tga", "oldpepe.tga", "OMEGAEZ.tga", "oniongang.tga", "PAUSERS.tga", "peep.tga",
      "peepaGrown.tga", "peepaKiss.tga", "peepaSexy.tga", "PeepGiggle.tga", "PeepHand.tga", "PeepKek.tga",
      "PeepLaugh.tga", "peepoAlliance.tga", "peepoAP.tga", "peepoBaba.tga", "peepoBeer.tga", "peepoBlanket.tga",
      "peepoBlankey.tga", "peepoBlush.tga", "peepoBlushing.tga", "peepoBored.tga", "peepoBritish.tga", "peepoBye.tga",
      "peepoCharge.tga", "peepoCheer.tga", "peepoChonk.tga", "peepoChop.tga", "peepoClap.tga", "peepoCN.tga",
      "peepoComfy.tga", "peepoCringe.tga", "peepoCrown.tga", "peepoCute.tga", "peepoDab.tga", "peepoDE.tga",
      "peepoDetective.tga", "peepoDetective2.tga", "peepoEhm.tga", "peepoES.tga", "peepoEU.tga", "peepoEvilSip.tga",
      "peepoExit.tga", "peepoEyes.tga", "peepoEZ.tga", "peepoFA.tga", "peepoFat.tga", "peepoFH.tga",
      "peepoFight.tga", "peepoFoil.tga", "peepoFR1.tga", "peepoFR2.tga", "peepoFriends.tga", "peepoFrogHappy.tga",
      "peepoGhost.tga", "peepoGift.tga", "peepoGiggle.tga", "peepoGlad.tga", "peepoGroovie.tga", "peepoGun.tga",
      "peepoH.tga", "peepoHands.tga", "peepoHappy.tga", "peepoHeart.tga", "peepoHeHe.tga", "peepoHey.tga",
      "peepoHide.tga", "peepoHmm.tga", "peepoHorse.tga", "peepoHug.tga", "peepoHugged.tga", "peepoHuggiesL.tga",
      "peepoHuggiesR.tga", "peepoIgnore.tga", "peepoIsForMe.tga", "peepoJail.tga", "peepoJammies.tga", "peepoJedi.tga",
      "peepoJorts.tga", "peepoJudge.tga", "peepoJuice.tga", "peepOK.tga", "peepoKEKW.tga", "peepoKing.tga",
      "peepoKiss.tga", "peepoKnight.tga", "peepoLip.tga", "peepoLoser.tga", "peepoLove.tga", "peepoM.tga",
      "peepoMadder.tga", "peepoMaybe.tga", "peepoNice.tga", "peepoNo.tga", "peepoNolegs.tga", "peepoNOO.tga",
      "peepoNOOO.tga", "peepoNotes.tga", "peepoOK.tga", "peepoPanda.tga", "peepoPants.tga", "peepoParty.tga",
      "peepoPat.tga", "peepoPee.tga", "peepoPeek.tga", "peepoPing.tga", "peepoPlease.tga", "peepoPlot.tga",
      "peepoPogPoo.tga", "peepoPoint.tga", "peepoPolice.tga", "peepoPoo.tga", "peepoPopcorn.tga", "peepoPride.tga",
      "peepoRain.tga", "peepoReallyHappy.tga", "peepoRiot.tga", "peepoS.tga", "PeepoSad.tga", "peepoSadCat.tga",
      "peepoSadLogize.tga", "peepoSalute.tga", "peepoScam.tga", "peepoSE.tga", "peepoSenor.tga", "peepoShake.tga",
      "peepoShower.tga", "peepoShrug.tga", "peepoShy.tga", "peepoSick.tga", "peepoSimp.tga", "peepoSimping.tga",
      "peepoSip.tga", "peepoSith.tga", "peepoSleepo.tga", "peepoSmash.tga", "peepoSmile.tga", "peepoSoup.tga",
      "peepoSPopcorn.tga", "peepoStab.tga", "peepoStonks.tga", "peepoStrong.tga", "peepoStudy.tga", "peepoSure.tga",
      "peepoSuspect.tga", "peepoSuspicious.tga", "peepoSweat.tga", "peepoTeddy.tga", "peepoTeeth.tga", "peepoThink.tga",
      "peepoTip.tga", "peepoTired.tga", "peepoTrash.tga", "peepoUgh.tga", "peepoUK.tga", "peepoUSA.tga",
      "peepoV.tga", "peepoWave.tga", "peepoWeird.tga", "peepoWeirdCrown.tga", "peepoWhy.tga", "peepoWoW.tga",
      "peepoWTF.tga", "PepeAyy.tga", "PepeBean.tga", "pepeBlyat.tga", "pepeBruh.tga", "PepeButt.tga",
      "PepeCat.tga", "PepeCatGun.tga", "PepeCatHeart.tga", "PepeCoffee.tga", "PepeCoolStory.tga", "PepeCozy.tga",
      "PepeD.tga", "PepeDent.tga", "PepeDisgust.tga", "PepeDribble.tga", "PepeFeet.tga", "PepeFinger.tga",
      "PepeFist.tga", "PepeFlushed.tga", "PepeFork.tga", "PepeFrench.tga", "PepeFU.tga", "PepeFuming.tga",
      "PepeG.tga", "Pepega.tga", "PepegaCredit.tga", "PepegaHammer.tga", "PepegaHands.tga", "PepegaKMS.tga",
      "PepegaLaugh.tga", "PepeGamer.tga", "pepeGang.tga", "PepegaPoo.tga", "PepegaS.tga", "PepegaSad.tga",
      "Pepege.tga", "PepegeS.tga", "PepegeSit.tga", "PepegeWeird.tga", "Pepeggers.tga", "Pepegwa.tga",
      "pepeHam.tga", "PepeHands.tga", "PepeHard.tga", "PepeHeart.tga", "PepeHug.tga", "PepeIgnore.tga",
      "PepeJAM.tga", "PepeKMS.tga", "PepeL.tga", "PepeLa.tga", "PepeLaffe.tga", "PepeLaugh.tga",
      "PepeLegs.tga", "PepeLMAO.tga", "PepeLoser.tga", "PepeLove.tga", "PepeM.tga", "PepeManos.tga",
      "PepeMegaSad.tga", "PepeMeltdown.tga", "PepeMods.tga", "PepeMStache.tga", "PepeNo.tga", "PepeNOOO.tga",
      "pepeNotOK.tga", "pepeOK.tga", "PepeOuuuhh.tga", "Pepepains.tga", "PepePants.tga", "PepePhone.tga",
      "PepePhoned.tga", "PepePlan.tga", "PepePoint.tga", "PepePoo.tga", "PepePopcorn.tga", "PePeppaPig.tga",
      "PepePuke.tga", "PepePyroblast.tga", "PepeReach.tga", "PepeRun.tga", "PepeScoots.tga", "PepeScout.tga",
      "PepeSith.tga", "PepeSlice.tga", "PepeSmile.tga", "PepeSmoke.tga", "pepeStepBro.tga", "PepeStressed.tga",
      "PepeTHICC.tga", "PepeThumbsUp.tga", "PepeUnicorn.tga", "pepeW.tga", "PepeWhip.tga", "PepeWizard.tga",
      "PepeWot.tga", "PepeXD.tga", "PepeYes.tga", "pepoEZ.tga", "pepoGun.tga", "pepohide.tga",
      "PepOMEGA.tga", "pepoS.tga", "pepoScience.tga", "PepoThink.tga", "PepperHands.tga", "pillowJammies.tga",
      "Plotge.tga", "pogg.tga", "POGGERS.tga", "POGGERSF.tga", "PoggersHype.tga", "PoggersHypeF.tga",
      "POGGERSLove.tga", "POGGIES.tga", "PogO2.tga", "POOGERS.tga", "PPepoCool.tga", "PPepoHit.tga",
      "ppEZ.tga", "ppFootbol.tga", "ppHop.tga", "ppSmoke.tga", "Prayge.tga", "RandomPepe.tga",
      "Ratge.tga", "Readge.tga", "REEE.tga", "Riotge.tga", "SadBlanket.tga", "Sadga.tga",
      "Sadge.tga", "sadgers.tga", "SadHonk.tga", "sadhug.tga", "SadJAM.tga", "SadLove.tga",
      "SadPepe.tga", "SAJ.tga", "sajj.tga", "SALAMI.tga", "salutt.tga", "SchubertaBruh.tga",
      "SchubertBruh.tga", "SchubertSmile.tga", "shadowChatting.tga", "shrujj.tga", "shy.tga", "skip.tga",
      "Smadge.tga", "Smilers.tga", "Smoge.tga", "SMUGGERS.tga", "SmugPepe.tga", "soupchamp.tga",
      "spit1.tga", "spit2.tga", "Starege.tga", "Stronge.tga", "SucksMan.tga", "Susge.tga",
      "Suske.tga", "Sussy.tga", "thehmm.tga", "thethink.tga", "Thinkge.tga", "TiredW.tga",
      "tomatogang.tga", "TOSga.tga", "TroggHYPERS.tga", "UHM.tga", "Voidge.tga", "Weirders.tga",
      "Weirdga.tga", "Weirdge.tga", "WeirdJAM.tga", "WeirdU.tga", "WeirdW.tga", "WICKED.tga",
      "WickedDrip.tga", "WICKEDSTEER.tga", "Wipege.tga", "WOAW.tga", "Wokege.tga", "Wokegesus.tga",
      "YEP.tga", "Yepge.tga", "YEPPERS.tga", "YIKERS.tga",
    },
    },
    { name = "FojjiCore: Speedrun", root = FOJJI_ROOT, addon = "FojjiCore", path = "Speedrun\\", files = {
      "boss\\akama.tga", "boss\\akilzon.tga", "boss\\alar.tga", "boss\\anetheron.tga", "boss\\archimonde.tga", "boss\\azgalor.tga",
      "boss\\brutallus.tga", "boss\\council.tga", "boss\\felmyst.tga", "boss\\gruul.tga", "boss\\gurtogg.tga", "boss\\hydross.tga",
      "boss\\illidan.tga", "boss\\janalai.tga", "boss\\kaelthas.tga", "boss\\kalecgos.tga", "boss\\karathress.tga", "boss\\kazrogal.tga",
      "boss\\kiljaedan.tga", "boss\\leotheras.tga", "boss\\lurker.tga", "boss\\magtheridon.tga", "boss\\malacrass.tga", "boss\\malchezar.tga",
      "boss\\muru.tga", "boss\\n1107.tga", "boss\\n1108.tga", "boss\\n1109.tga", "boss\\n1110.tga", "boss\\n1111.tga",
      "boss\\n1112.tga", "boss\\n1113.tga", "boss\\n1114.tga", "boss\\n1115.tga", "boss\\n1116.tga", "boss\\n1117.tga",
      "boss\\n1118.tga", "boss\\n1119.tga", "boss\\n1120.tga", "boss\\n1121.tga", "boss\\najentus.tga", "boss\\nalorakk.tga",
      "boss\\opera.tga", "boss\\ragewinterchill.tga", "boss\\reliquary.tga", "boss\\shahraz.tga", "boss\\solarian.tga", "boss\\supremus.tga",
      "boss\\teron.tga", "boss\\tidewalker.tga", "boss\\twins.tga", "boss\\vashj.tga", "boss\\voidreaver.tga", "boss\\zuljin.tga",
      "check.tga", "chevron.tga", "gear.tga", "instance\\109.tga", "instance\\129.tga", "instance\\189.tga",
      "instance\\209.tga", "instance\\229.tga", "instance\\230.tga", "instance\\249.tga", "instance\\269.tga", "instance\\289.tga",
      "instance\\2959.tga", "instance\\2998.tga", "instance\\2999.tga", "instance\\3065.tga", "instance\\329.tga", "instance\\33.tga",
      "instance\\34.tga", "instance\\349.tga", "instance\\36.tga", "instance\\389.tga", "instance\\409.tga", "instance\\429.tga",
      "instance\\43.tga", "instance\\469.tga", "instance\\47.tga", "instance\\48.tga", "instance\\509.tga", "instance\\531.tga",
      "instance\\532.tga", "instance\\533.tga", "instance\\534.tga", "instance\\540.tga", "instance\\542.tga", "instance\\543.tga",
      "instance\\544.tga", "instance\\545.tga", "instance\\546.tga", "instance\\547.tga", "instance\\548.tga", "instance\\550.tga",
      "instance\\552.tga", "instance\\553.tga", "instance\\554.tga", "instance\\555.tga", "instance\\556.tga", "instance\\557.tga",
      "instance\\558.tga", "instance\\560.tga", "instance\\564.tga", "instance\\565.tga", "instance\\568.tga", "instance\\580.tga",
      "instance\\585.tga", "instance\\70.tga", "instance\\90.tga", "play.tga", "reset.tga", "stop.tga",
    },
    },
    { name = "FojjiCore: TBC Icon", root = FOJJI_ROOT, addon = "FojjiCore", path = "TBC Icon\\", files = {
      "Abomination.png", "Banshee.png", "CryptFiend.png", "FrostWyrm.png", "Gargoyle.png", "Ghoul.png",
      "Jaina.png", "Necromancer.png", "Thrall.png",
    },
    },
    { name = "FojjiCore: Themes", root = FOJJI_ROOT, addon = "FojjiCore", path = "Themes\\", files = {
      "glow-radial.tga", "pat-diag.tga", "pat-dots.tga", "pat-grid.tga", "pat-hex.tga", "pat-leaves.tga",
      "pat-scales.tga", "pat-sparkle.tga", "pat-stars.tga",
    },
    },
    { name = "FojjiCore: Throne of Thunder", root = FOJJI_ROOT, addon = "FojjiCore", path = "Throne of Thunder\\", files = {
      "ArcaneSnek.png", "ArrowDown.png", "ArrowDownWhite.png", "ArrowDownWhite.tga", "ArrowUp.png", "ArrowUpWhite.png",
      "ArrowUpWhite.tga", "FireSnek.png", "FrostSnek.png", "GarySnail.png", "MarioKart1.png", "MarioKart2.png",
      "MarioKart3.png", "MarioKartGraphicsGo.png", "NatureSnek.png", "Shell-Green-icon.png", "TwinsOverlayChiji.png", "TwinsOverlayNiuzao.png",
      "TwinsOverlayXuen.png", "TwinsOverlayYulon.png", "TwinsRoom.png",
    },
    },
    { name = "FojjiCore: UI", root = FOJJI_ROOT, addon = "FojjiCore", path = "UI\\", files = {
      "anchor.blp", "arrow-down.blp", "arrow-up-down.blp", "arrow-up.blp", "badge-disc.tga", "badge-glow.tga",
      "badge-ring.tga", "bell.blp", "calendar.blp", "check.blp", "chevron-down.blp", "chevron-left.blp",
      "chevron-right.blp", "chevron-up.blp", "clock.blp", "close-cross.tga", "copy.blp", "download.blp",
      "external-link.blp", "eye-off.blp", "eye.blp", "funnel.blp", "glow-blob.tga", "glow-soft.tga",
      "grad-h.tga", "grad-v.tga", "grip-vertical.blp", "header-edge.tga", "header-light.tga", "header-metal.tga",
      "heart.blp", "icon-bis.tga", "icon-check.tga", "icon-chevron-down.tga", "icon-chevron-right.tga", "icon-chevron-up.tga",
      "icon-drop.tga", "icon-export.tga", "icon-font.tga", "icon-gear.tga", "icon-gossip.tga", "icon-info.tga",
      "icon-journal.tga", "icon-key.tga", "icon-link.tga", "icon-minus.tga", "icon-palette.tga", "icon-play.tga",
      "icon-plus.tga", "icon-raid.tga", "icon-reset.tga", "icon-search.tga", "icon-speaker.tga", "icon-stop.tga",
      "icon-stopwatch.tga", "icon-timeline.tga", "info.blp", "link.blp", "lock-open.blp", "lock.blp",
      "menu.blp", "minus.blp", "nav-about.tga", "nav-arrow-glow.tga", "nav-arrow.tga", "nav-bis.tga",
      "nav-disc.tga", "nav-djsettings.tga", "nav-dungeonjournal.tga", "nav-font.tga", "nav-general.tga", "nav-guide.tga",
      "nav-modules.tga", "nav-raidlead.tga", "nav-ring.tga", "nav-scale.tga", "nav-speedrun.tga", "nav-spellranks.tga",
      "nav-tts.tga", "nav-worldroutes.tga", "ornament-diamond.tga", "panel-corner.tga", "panel-grain.tga", "pause.blp",
      "pencil.blp", "pin.blp", "play.blp", "play_icon.blp", "plus.blp", "refresh-cw.blp",
      "rotate-ccw.blp", "save.blp", "search.blp", "settings.blp", "shadow-corner.tga", "shadow-h.tga",
      "shadow-v.tga", "shield.blp", "skull.blp", "social-chat.tga", "social-discord.tga", "social-gift.tga",
      "social-heart.tga", "social-patreon.tga", "social-paypal.tga", "social-stream.tga", "social-twitch.tga", "star.blp",
      "stop_icon.blp", "swords.blp", "trash-2.blp", "triangle-alert.blp", "upload.blp", "user-round.blp",
      "user.blp", "users-round.blp", "users.blp", "x.blp",
    },
    },
  },
}
